import land1 from "../../../../assets/images/nfts/land.webp";
import land2 from "../../../../assets/images/nfts/land2.webp";
import land3 from "../../../../assets/images/nfts/land3.webp";
import land4 from "../../../../assets/images/nfts/land4.webp";
import land5 from "../../../../assets/images/nfts/land5.webp";
import land6 from "../../../../assets/images/nfts/land6.webp";
import land7 from "../../../../assets/images/nfts/land7.webp";
import land8 from "../../../../assets/images/nfts/land8.webp";
const landData = [
  {
    id: 25,
    nft: land1,
    NFTalt: "A land-themed NFT",
    OwnerName: "LandOwner #1234",
    OwnerSorName: "LandOwner",
    FromBid: "1.25 ETH",
    LatestBid: "2.75 ETH",
    TotalBids: "$15,345",
    Profits: "+7.42%",
    Collection: "Land",
  },
  {
    id: 26,
    nft: land2,
    NFTalt: "A land-themed NFT",
    OwnerName: "LandOwner #5678",
    OwnerSorName: "LandOwner",
    FromBid: "1.50 ETH",
    LatestBid: "3.25 ETH",
    TotalBids: "$18,345",
    Profits: "+8.92%",
    Collection: "Land",
  },
  {
    id: 27,
    nft: land3,
    NFTalt: "A land-themed NFT",
    OwnerName: "LandOwner #9012",
    OwnerSorName: "LandOwner",
    FromBid: "2.00 ETH",
    LatestBid: "4.50 ETH",
    TotalBids: "$22,345",
    Profits: "+10.43%",
    Collection: "Land",
  },
  {
    id: 28,
    nft: land4,
    NFTalt: "A land-themed NFT",
    OwnerName: "LandOwner #3456",
    OwnerSorName: "LandOwner",
    FromBid: "1.75 ETH",
    LatestBid: "3.75 ETH",
    TotalBids: "$19,345",
    Profits: "+9.21%",
    Collection: "Land",
  },
  {
    id: 29,
    nft: land5,
    NFTalt: "A land-themed NFT",
    OwnerName: "LandOwner #7890",
    OwnerSorName: "LandOwner",
    FromBid: "1.95 ETH",
    LatestBid: "4.25 ETH",
    TotalBids: "$20,345",
    Profits: "+9.73%",
    Collection: "Land",
  },
  {
    id: 30,
    nft: land6,
    NFTalt: "A land-themed NFT",
    OwnerName: "LandOwner #2345",
    OwnerSorName: "LandOwner",
    FromBid: "2.50 ETH",
    LatestBid: "5.50 ETH",
    TotalBids: "$28,345",
    Profits: "+12.42%",
    Collection: "Land",
  },
  {
    id: 31,
    nft: land7,
    NFTalt: "A land-themed NFT",
    OwnerName: "LandOwner #6789",
    OwnerSorName: "LandOwner",
    FromBid: "2.75 ETH",
    LatestBid: "6.25 ETH",
    TotalBids: "$32,345",
    Profits: "+14.23%",
    Collection: "Land",
  },
  {
    id: 32,
    nft: land8,
    NFTalt: "A land-themed NFT",
    OwnerName: "LandOwner #0123",
    OwnerSorName: "LandOwner",
    FromBid: "2.25 ETH",
    LatestBid: "5.00 ETH",
    TotalBids: "$25,345",
    Profits: "+11.64%",
    Collection: "Land",
  },
];
export default landData;
