import purpleHair from "./"

const data2 = [
  {
    id: 1,
    nft: BGalaxy,
    NFTalt: "A galaxy, NFT",
    Owner: OB4,
    OwnerName: "CryptoNerd #1234",
    OwnerSorName: "CryptoNerd",
    OwnerAlt: "Profile of CryptoNerd",
    FromBid: "1.25 ETH",
    LatestBid: "2.75 ETH",
    TotalBids: "$15,345",
    Profits: "+7.42%",
    TimeLeft: "2 days 5 hours",
    Description:
      "This unique NFT features a stunning image of a galaxy, with vibrant colors and intricate details that will mesmerize any viewer. Own a piece of the universe today!",
    Tags: ["space", "galaxy", "art", "digital"],
    Collection: "Cosmic Wonders",
    Verified: true,
  },
  {
    id: 2,
    nft: BDog,
    NFTalt: "A dog, NFT",
    Owner: OB5,
    OwnerName: "PetLover #5678",
    OwnerSorName: "PetLover",
    OwnerAlt: "Profile of PetLover",
    FromBid: "0.75 ETH",
    LatestBid: "1.25 ETH",
    TotalBids: "$6,789",
    Profits: "+3.75%",
    TimeLeft: "1 day 12 hours",
    Description:
      "This adorable NFT features a cute little dog, with big eyes and a playful expression. Perfect for any animal lover!",
    Tags: ["dog", "pet", "art", "digital"],
    Collection: "Pet Portraits",
    Verified: true,
  },
  {
    id: 3,
    nft: BDragon,
    NFTalt: "A dragon, NFT",
    Owner: OB6,
    OwnerName: "FantasyFan #9999",
    OwnerSorName: "FantasyFan",
    OwnerAlt: "Profile of FantasyFan",
    FromBid: "10.00 ETH",
    LatestBid: "15.50 ETH",
    TotalBids: "$150,000",
    Profits: "+20.00%",
    TimeLeft: "3 days 7 hours",
    Description:
      "This epic NFT features a fierce dragon, with scales that shimmer in the light and wings that span the entire image. A must-have for any fantasy collector!",
    Tags: ["dragon", "fantasy", "art", "digital"],
    Collection: "Mythical Creatures",
    Verified: true,
  },
];
