import purpleHair from "../../../../assets/images/nfts/purpleHair.webp";
import Boy from "../../../../assets/images/nfts/Boy.webp";
import Cboy2Goast from "../../../../assets/images/nfts/Boy.webp";
import Cboy3 from "../../../../assets/images/nfts/Cboy3.webp";
import campGirl from "../../../../assets/images/nfts/campGirl.webp";
import moneyBear from "../../../../assets/images/nfts/moneyBear.webp";
import samori from "../../../../assets/images/nfts/samori.webp";
import whiteBear from "../../../../assets/images/nfts/whiteBear.webp";
import strangeObj1 from "../../../../assets/images/nfts/piDragon.webp";
import strangeObj2 from "../../../../assets/images/nfts/strange2.webp";
import strangeObj3 from "../../../../assets/images/nfts/strange21.webp";
import strangeObj4 from "../../../../assets/images/nfts/strange22.webp";
import strangeObj5 from "../../../../assets/images/nfts/image 23.webp";
import strangeObj6 from "../../../../assets/images/nfts/strange24.webp";
import strangeObj7 from "../../../../assets/images/nfts/strange1.webp";
import strangeObj8 from "../../../../assets/images/nfts/piCheap.webp";
import land1 from "../../../../assets/images/nfts/land.webp";
import land2 from "../../../../assets/images/nfts/land2.webp";
import land3 from "../../../../assets/images/nfts/land3.webp";
import land4 from "../../../../assets/images/nfts/land4.webp";
import land5 from "../../../../assets/images/nfts/land5.webp";
import land6 from "../../../../assets/images/nfts/land6.webp";
import land7 from "../../../../assets/images/nfts/land7.webp";
import land8 from "../../../../assets/images/nfts/land8.webp";
import sport1 from "../../../../assets/images/nfts/player.webp";
import sport2 from "../../../../assets/images/nfts/player2.webp";
import sport3 from "../../../../assets/images/nfts/player3.webp";
import sport4 from "../../../../assets/images/nfts/player4.webp";
import sport5 from "../../../../assets/images/nfts/player5.webp";
import sport6 from "../../../../assets/images/nfts/player6.webp";
import sport7 from "../../../../assets/images/nfts/player7.webp";
import sport8 from "../../../../assets/images/nfts/player8.webp";
import more1 from "../../../../assets/images/nfts/goast1.webp";
import more2 from "../../../../assets/images/nfts/goast3.webp";
import more3 from "../../../../assets/images/nfts/goast4.webp";
import more4 from "../../../../assets/images/nfts/dogy.webp";
import more5 from "../../../../assets/images/nfts/dogy2.webp";
import more6 from "../../../../assets/images/nfts/cowboy.webp";
import more7 from "../../../../assets/images/nfts/cowboy5.webp";
import more8 from "../../../../assets/images/nfts/cowboy4.webp";
import space1 from "../../../../assets/images/nfts/space1.webp";
import space2 from "../../../../assets/images/nfts/space2.webp";
import space3 from "../../../../assets/images/nfts/space3.webp";
import space4 from "../../../../assets/images/nfts/space4.webp";
import space5 from "../../../../assets/images/nfts/space5.webp";
import space6 from "../../../../assets/images/nfts/space6.webp";
import space7 from "../../../../assets/images/nfts/space7.webp";
import space8 from "../../../../assets/images/nfts/space8.webp";

const artData = [
  //? ART
  {
    id: 1,
    nft: purpleHair,
    NFTalt: "A purple-haired girl, NFT",
    OwnerName: "CryptoNerd #1234",
    OwnerSorName: "CryptoNerd",
    FromBid: "1.25 ETH",
    LatestBid: "2.75 ETH",
    TotalBids: "$15,345",
    Profits: "+7.42%",
    Collection: "Art",
  },
  {
    id: 2,
    nft: Cboy2Goast,
    NFTalt: "A ghost boy, NFT",
    OwnerName: "PetLover #5678",
    OwnerSorName: "PetLover",
    FromBid: "0.75 ETH",
    LatestBid: "1.25 ETH",
    TotalBids: "$6,789",
    Profits: "+3.75%",
    Collection: "Art",
  },
  {
    id: 3,
    nft: Cboy3,
    NFTalt: "A boy with a hat, NFT",
    OwnerName: "FantasyFan #9999",
    OwnerSorName: "FantasyFan",
    FromBid: "10.00 ETH",
    LatestBid: "15.50 ETH",
    TotalBids: "$150,000",
    Profits: "+20.00%",
    Collection: "Art",
  },
  {
    id: 4,
    nft: campGirl,
    NFTalt: "A girl in a tent, NFT",
    OwnerName: "ArtLover #2468",
    OwnerSorName: "ArtLover",
    FromBid: "1.50 ETH",
    LatestBid: "2.00 ETH",
    TotalBids: "$10,000",
    Profits: "+5.00%",
    Collection: "Art",
  },
  {
    id: 5,
    nft: samori,
    NFTalt: "A samurai, NFT",
    OwnerName: "SamuraiFan #1357",
    OwnerSorName: "SamuraiFan",
    FromBid: "5.00 ETH",
    LatestBid: "10.00 ETH",
    TotalBids: "$50,000",
    Profits: "+15.00%",
    Collection: "Art",
  },
  {
    id: 6,
    nft: whiteBear,
    NFTalt: "A white bear, NFT",
    OwnerName: "AnimalLover #8642",
    OwnerSorName: "AnimalLover",
    FromBid: "2.00 ETH",
    LatestBid: "3.50 ETH",
    TotalBids: "$20,000",
    Profits: "+10.00%",
    Collection: "Art",
  },
  {
    id: 7,
    nft: Boy,
    NFTalt: "A boy with headphones, NFT",
    OwnerName: "MusicLover #7531",
    OwnerSorName: "MusicLover",
    FromBid: "3.00 ETH",
    LatestBid: "5.00 ETH",
    TotalBids: "$30,000",
    Profits: "+12.50%",
    Collection: "Art",
  },
  {
    id: 8,
    nft: moneyBear,
    NFTalt: "A bear with a dollar sign, NFT",
    OwnerName: "CryptoLover #2468",
    OwnerSorName: "CryptoLover",
    FromBid: "0.50 ETH",
    LatestBid: "1.00 ETH",
    TotalBids: "$5,000",
    Profits: "+2.50%",
    Collection: "Art",
  },
];
const collData = [
  {
    id: 9,
    nft: strangeObj1,
    NFTalt: "A strange object, NFT",
    OwnerName: "MysteryLover #9753",
    OwnerSorName: "MysteryLover",
    FromBid: "7.50 ETH",
    LatestBid: "12.00 ETH",
    TotalBids: "$100,000",
    Profits: "+25.00%",
    Collection: "Collectibles",
  },
  {
    id: 10,
    nft: strangeObj2,
    NFTalt: "A strange object, NFT",
    OwnerName: "MysteryLover #9753",
    OwnerSorName: "MysteryLover",
    FromBid: "7.50 ETH",
    LatestBid: "12.00 ETH",
    TotalBids: "$100,000",
    Profits: "+25.00%",
    Collection: "Collectibles",
  },
  {
    id: 11,
    nft: strangeObj3,
    NFTalt: "A strange object, NFT",
    OwnerName: "MysteryLover #9753",
    OwnerSorName: "MysteryLover",
    FromBid: "7.50 ETH",
    LatestBid: "12.00 ETH",
    TotalBids: "$100,000",
    Profits: "+25.00%",
    Collection: "Collectibles",
  },
  {
    id: 12,
    nft: strangeObj4,
    NFTalt: "A strange object, NFT",
    OwnerName: "MysteryLover #9753",
    OwnerSorName: "MysteryLover",
    FromBid: "7.50 ETH",
    LatestBid: "12.00 ETH",
    TotalBids: "$100,000",
    Profits: "+25.00%",
    Collection: "Collectibles",
  },
  {
    id: 13,
    nft: strangeObj5,
    NFTalt: "A strange object, NFT",
    OwnerName: "MysteryLover #9753",
    OwnerSorName: "MysteryLover",
    FromBid: "7.50 ETH",
    LatestBid: "12.00 ETH",
    TotalBids: "$100,000",
    Profits: "+25.00%",
    Collection: "Collectibles",
  },
  {
    id: 14,
    nft: strangeObj6,
    NFTalt: "A strange object, NFT",
    OwnerName: "MysteryLover #9753",
    OwnerSorName: "MysteryLover",
    FromBid: "7.50 ETH",
    LatestBid: "12.00 ETH",
    TotalBids: "$100,000",
    Profits: "+25.00%",
    Collection: "Collectibles",
  },
  {
    id: 15,
    nft: strangeObj7,
    NFTalt: "A dragon, NFT",
    OwnerName: "DragonLover #2468",
    OwnerSorName: "DragonLover",
    FromBid: "2.50 ETH",
    LatestBid: "5.00 ETH",
    TotalBids: "$25,000",
    Profits: "+10.00%",
    Collection: "Collectibles",
  },
  {
    id: 16,
    nft: strangeObj8,
    NFTalt: "A cheap robot, NFT",
    OwnerName: "RobotFan #1357",
    OwnerSorName: "RobotFan",
    FromBid: "0.50 ETH",
    LatestBid: "1.00 ETH",
    TotalBids: "$2,500",
    Profits: "+5.00%",
    Collection: "Collectibles",
  },
];

const spaceData = [
  {
    id: 17,
    nft: space1,
    NFTalt: "A space-themed NFT",
    OwnerName: "CryptoNerd #1234",
    OwnerSorName: "CryptoNerd",
    FromBid: "1.25 ETH",
    LatestBid: "2.75 ETH",
    TotalBids: "$15,345",
    Profits: "+7.42%",
    Collection: "Space",
  },
  {
    id: 18,
    nft: space2,
    NFTalt: "Another space-themed NFT",
    OwnerName: "CryptoGeek #5678",
    OwnerSorName: "CryptoGeek",
    FromBid: "0.75 ETH",
    LatestBid: "1.50 ETH",
    TotalBids: "$8,940",
    Profits: "+12.87%",
    Collection: "Space",
  },
  {
    id: 19,
    nft: space3,
    NFTalt: "Yet another space-themed NFT",
    OwnerName: "CryptoCollector #9012",
    OwnerSorName: "CryptoCollector",
    FromBid: "3.50 ETH",
    LatestBid: "4.25 ETH",
    TotalBids: "$22,560",
    Profits: "+5.21%",
    Collection: "Space",
  },
  {
    id: 20,
    nft: space4,
    NFTalt: "A fourth space-themed NFT",
    OwnerName: "CryptoInvestor #5555",
    OwnerSorName: "CryptoInvestor",
    FromBid: "2.00 ETH",
    LatestBid: "3.50 ETH",
    TotalBids: "$19,875",
    Profits: "+8.63%",
    Collection: "Space",
  },
  {
    id: 21,
    nft: space5,
    NFTalt: "Yet another space-themed NFT",
    OwnerName: "CryptoTrader #2468",
    OwnerSorName: "CryptoTrader",
    FromBid: "1.50 ETH",
    LatestBid: "2.75 ETH",
    TotalBids: "$14,560",
    Profits: "+6.21%",
    Collection: "Space",
  },
  {
    id: 22,
    nft: space6,
    NFTalt: "A sixth space-themed NFT",
    OwnerName: "CryptoHodler #3691",
    OwnerSorName: "CryptoHodler",
    FromBid: "4.00 ETH",
    LatestBid: "5.50 ETH",
    TotalBids: "$28,120",
    Profits: "+9.87%",
    Collection: "Space",
  },
  {
    id: 23,
    nft: space7,
    NFTalt: "Another space-themed NFT",
    OwnerName: "CryptoEnthusiast #7777",
    OwnerSorName: "CryptoEnthusiast",
    FromBid: "0.50 ETH",
    LatestBid: "1.00 ETH",
    TotalBids: "$7,560",
    Profits: "+14.87%",
    Collection: "Space",
  },
  {
    id: 24,
    nft: space8,
    NFTalt: "A final space-themed NFT",
    OwnerName: "CryptoFan #8888",
    OwnerSorName: "CryptoFan",
    FromBid: "3.25 ETH",
    LatestBid: "4.50 ETH",
    TotalBids: "$24,560",
    Profits: "+11.21%",
    Collection: "Space",
  },
];
const sportData = [
  {
    id: 33,
    nft: sport1,
    NFTalt: "A sport NFT",
    OwnerName: "SportOwner #1234",
    OwnerSorName: "SportOwner",
    FromBid: "0.5 ETH",
    LatestBid: "1.25 ETH",
    TotalBids: "$10,000",
    Profits: "+10.00%",
    Collection: "Sports Collection",
  },
  {
    id: 34,
    nft: sport2,
    NFTalt: "A sport NFT",
    OwnerName: "SportOwner #5678",
    OwnerSorName: "SportOwner",
    FromBid: "0.75 ETH",
    LatestBid: "2.00 ETH",
    TotalBids: "$20,000",
    Profits: "+15.00%",
    Collection: "Sports Collection",
  },
  {
    id: 35,
    nft: sport3,
    NFTalt: "A sport NFT",
    OwnerName: "SportOwner #9012",
    OwnerSorName: "SportOwner",
    FromBid: "1.00 ETH",
    LatestBid: "2.50 ETH",
    TotalBids: "$30,000",
    Profits: "+20.00%",
    Collection: "Sports Collection",
  },
  {
    id: 36,
    nft: sport4,
    NFTalt: "A sport NFT",
    OwnerName: "SportOwner #3456",
    OwnerSorName: "SportOwner",
    FromBid: "0.25 ETH",
    LatestBid: "1.00 ETH",
    TotalBids: "$5,000",
    Profits: "+5.00%",
    Collection: "Sports Collection",
  },
  {
    id: 37,
    nft: sport5,
    NFTalt: "A sport NFT",
    OwnerName: "SportOwner #7890",
    OwnerSorName: "SportOwner",
    FromBid: "0.50 ETH",
    LatestBid: "1.50 ETH",
    TotalBids: "$15,000",
    Profits: "+12.50%",
    Collection: "Sports Collection",
  },
  {
    id: 38,
    nft: sport6,
    NFTalt: "A sport NFT",
    OwnerName: "SportOwner #2345",
    OwnerSorName: "SportOwner",
    FromBid: "0.75 ETH",
    LatestBid: "2.25 ETH",
    TotalBids: "$25,000",
    Profits: "+17.50%",
    Collection: "Sports Collection",
  },
  {
    id: 39,
    nft: sport7,
    NFTalt: "A sport NFT",
    OwnerName: "SportOwner #6789",
    OwnerSorName: "SportOwner",
    FromBid: "1.00 ETH",
    LatestBid: "3.00 ETH",
    TotalBids: "$35,000",
    Profits: "+25.00%",
    Collection: "Sports Collection",
  },
  {
    id: 40,
    nft: sport8,
    NFTalt: "A sport NFT",
    OwnerName: "SportOwner #1234",
    OwnerSorName: "SportOwner",
    FromBid: "0.25 ETH",
    LatestBid: "0.75 ETH",
    TotalBids: "$2,500",
    Profits: "+2.50%",
    Collection: "Sports Collection",
  },
];
const landData = [
  {
    id: 25,
    nft: land1,
    NFTalt: "A land-themed NFT",
    OwnerName: "LandOwner #1234",
    OwnerSorName: "LandOwner",
    FromBid: "1.25 ETH",
    LatestBid: "2.75 ETH",
    TotalBids: "$15,345",
    Profits: "+7.42%",
    Collection: "Land",
  },
  {
    id: 26,
    nft: land2,
    NFTalt: "A land-themed NFT",
    OwnerName: "LandOwner #5678",
    OwnerSorName: "LandOwner",
    FromBid: "1.50 ETH",
    LatestBid: "3.25 ETH",
    TotalBids: "$18,345",
    Profits: "+8.92%",
    Collection: "Land",
  },
  {
    id: 27,
    nft: land3,
    NFTalt: "A land-themed NFT",
    OwnerName: "LandOwner #9012",
    OwnerSorName: "LandOwner",
    FromBid: "2.00 ETH",
    LatestBid: "4.50 ETH",
    TotalBids: "$22,345",
    Profits: "+10.43%",
    Collection: "Land",
  },
  {
    id: 28,
    nft: land4,
    NFTalt: "A land-themed NFT",
    OwnerName: "LandOwner #3456",
    OwnerSorName: "LandOwner",
    FromBid: "1.75 ETH",
    LatestBid: "3.75 ETH",
    TotalBids: "$19,345",
    Profits: "+9.21%",
    Collection: "Land",
  },
  {
    id: 29,
    nft: land5,
    NFTalt: "A land-themed NFT",
    OwnerName: "LandOwner #7890",
    OwnerSorName: "LandOwner",
    FromBid: "1.95 ETH",
    LatestBid: "4.25 ETH",
    TotalBids: "$20,345",
    Profits: "+9.73%",
    Collection: "Land",
  },
  {
    id: 30,
    nft: land6,
    NFTalt: "A land-themed NFT",
    OwnerName: "LandOwner #2345",
    OwnerSorName: "LandOwner",
    FromBid: "2.50 ETH",
    LatestBid: "5.50 ETH",
    TotalBids: "$28,345",
    Profits: "+12.42%",
    Collection: "Land",
  },
  {
    id: 31,
    nft: land7,
    NFTalt: "A land-themed NFT",
    OwnerName: "LandOwner #6789",
    OwnerSorName: "LandOwner",
    FromBid: "2.75 ETH",
    LatestBid: "6.25 ETH",
    TotalBids: "$32,345",
    Profits: "+14.23%",
    Collection: "Land",
  },
  {
    id: 32,
    nft: land8,
    NFTalt: "A land-themed NFT",
    OwnerName: "LandOwner #0123",
    OwnerSorName: "LandOwner",
    FromBid: "2.25 ETH",
    LatestBid: "5.00 ETH",
    TotalBids: "$25,345",
    Profits: "+11.64%",
    Collection: "Land",
  },
];
const moreData = [
  {
    id: 41,
    nft: more1,
    NFTalt: "A goast NFT",
    OwnerName: "GoastOwner #1234",
    OwnerSorName: "GoastOwner",
    FromBid: "0.5 ETH",
    LatestBid: "1.25 ETH",
    TotalBids: "$10,000",
    Profits: "+10.00%",
    Collection: "Goast Collection",
  },
  {
    id: 42,
    nft: more2,
    NFTalt: "A goast NFT",
    OwnerName: "GoastOwner #5678",
    OwnerSorName: "GoastOwner",
    FromBid: "0.75 ETH",
    LatestBid: "2.00 ETH",
    TotalBids: "$20,000",
    Profits: "+15.00%",
    Collection: "Goast Collection",
  },
  {
    id: 43,
    nft: more3,
    NFTalt: "A goast NFT",
    OwnerName: "GoastOwner #9012",
    OwnerSorName: "GoastOwner",
    FromBid: "1.00 ETH",
    LatestBid: "2.50 ETH",
    TotalBids: "$30,000",
    Profits: "+20.00%",
    Collection: "Goast Collection",
  },
  {
    id: 44,
    nft: more4,
    NFTalt: "A dog NFT",
    OwnerName: "DogOwner #3456",
    OwnerSorName: "DogOwner",
    FromBid: "0.25 ETH",
    LatestBid: "1.00 ETH",
    TotalBids: "$5,000",
    Profits: "+5.00%",
    Collection: "Dog Collection",
  },
  {
    id: 45,
    nft: more5,
    NFTalt: "A dog NFT",
    OwnerName: "DogOwner #7890",
    OwnerSorName: "DogOwner",
    FromBid: "0.50 ETH",
    LatestBid: "1.50 ETH",
    TotalBids: "$15,000",
    Profits: "+12.50%",
    Collection: "Dog Collection",
  },
  {
    id: 46,
    nft: more6,
    NFTalt: "A cowboy NFT",
    OwnerName: "CowboyOwner #2345",
    OwnerSorName: "CowboyOwner",
    FromBid: "0.75 ETH",
    LatestBid: "2.25 ETH",
    TotalBids: "$25,000",
    Profits: "+17.50%",
    Collection: "Cowboy Collection",
  },
  {
    id: 47,
    nft: more7,
    NFTalt: "A cowboy NFT",
    OwnerName: "CowboyOwner #6789",
    OwnerSorName: "CowboyOwner",
    FromBid: "1.00 ETH",
    LatestBid: "3.00 ETH",
    TotalBids: "$35,000",
    Profits: "+25.00%",
    Collection: "Cowboy Collection",
  },
  {
    id: 48,
    nft: more8,
    NFTalt: "A cowboy NFT",
    OwnerName: "CowboyOwner #1234",
    OwnerSorName: "CowboyOwner",
    FromBid: "0.25 ETH",
    LatestBid: "0.75 ETH",
    TotalBids: "$2,500",
    Profits: "+2.50%",
    Collection: "Cowboy Collection",
  },
];

export { artData, collData, spaceData, sportData, landData, moreData };
