import more1 from "../../../../assets/images/nfts/goast1.webp";
import more2 from "../../../../assets/images/nfts/goast3.webp";
import more3 from "../../../../assets/images/nfts/goast4.webp";
import more4 from "../../../../assets/images/nfts/dogy.webp";
import more5 from "../../../../assets/images/nfts/dogy2.webp";
import more6 from "../../../../assets/images/nfts/cowboy.webp";
import more7 from "../../../../assets/images/nfts/cowboy5.webp";
import more8 from "../../../../assets/images/nfts/cowboy4.webp";
const moreData = [
  {
    id: 41,
    nft: more1,
    NFTalt: "A goast NFT",
    OwnerName: "GoastOwner #1234",
    OwnerSorName: "GoastOwner",
    FromBid: "0.5 ETH",
    LatestBid: "1.25 ETH",
    TotalBids: "$10,000",
    Profits: "+10.00%",
    Collection: "Goast Collection",
  },
  {
    id: 42,
    nft: more2,
    NFTalt: "A goast NFT",
    OwnerName: "GoastOwner #5678",
    OwnerSorName: "GoastOwner",
    FromBid: "0.75 ETH",
    LatestBid: "2.00 ETH",
    TotalBids: "$20,000",
    Profits: "+15.00%",
    Collection: "Goast Collection",
  },
  {
    id: 43,
    nft: more3,
    NFTalt: "A goast NFT",
    OwnerName: "GoastOwner #9012",
    OwnerSorName: "GoastOwner",
    FromBid: "1.00 ETH",
    LatestBid: "2.50 ETH",
    TotalBids: "$30,000",
    Profits: "+20.00%",
    Collection: "Goast Collection",
  },
  {
    id: 44,
    nft: more4,
    NFTalt: "A dog NFT",
    OwnerName: "DogOwner #3456",
    OwnerSorName: "DogOwner",
    FromBid: "0.25 ETH",
    LatestBid: "1.00 ETH",
    TotalBids: "$5,000",
    Profits: "+5.00%",
    Collection: "Dog Collection",
  },
  {
    id: 45,
    nft: more5,
    NFTalt: "A dog NFT",
    OwnerName: "DogOwner #7890",
    OwnerSorName: "DogOwner",
    FromBid: "0.50 ETH",
    LatestBid: "1.50 ETH",
    TotalBids: "$15,000",
    Profits: "+12.50%",
    Collection: "Dog Collection",
  },
  {
    id: 46,
    nft: more6,
    NFTalt: "A cowboy NFT",
    OwnerName: "CowboyOwner #2345",
    OwnerSorName: "CowboyOwner",
    FromBid: "0.75 ETH",
    LatestBid: "2.25 ETH",
    TotalBids: "$25,000",
    Profits: "+17.50%",
    Collection: "Cowboy Collection",
  },
  {
    id: 47,
    nft: more7,
    NFTalt: "A cowboy NFT",
    OwnerName: "CowboyOwner #6789",
    OwnerSorName: "CowboyOwner",
    FromBid: "1.00 ETH",
    LatestBid: "3.00 ETH",
    TotalBids: "$35,000",
    Profits: "+25.00%",
    Collection: "Cowboy Collection",
  },
  {
    id: 48,
    nft: more8,
    NFTalt: "A cowboy NFT",
    OwnerName: "CowboyOwner #1234",
    OwnerSorName: "CowboyOwner",
    FromBid: "0.25 ETH",
    LatestBid: "0.75 ETH",
    TotalBids: "$2,500",
    Profits: "+2.50%",
    Collection: "Cowboy Collection",
  },
];
export default moreData;
