import space1 from "../../../../assets/images/nfts/space1.webp";
import space2 from "../../../../assets/images/nfts/space2.webp";
import space3 from "../../../../assets/images/nfts/space3.webp";
import space4 from "../../../../assets/images/nfts/space4.webp";
import space5 from "../../../../assets/images/nfts/space5.webp";
import space6 from "../../../../assets/images/nfts/space6.webp";
import space7 from "../../../../assets/images/nfts/space7.webp";
import space8 from "../../../../assets/images/nfts/space8.webp";
const spaceData = [
  {
    id: 17,
    nft: space1,
    NFTalt: "A space-themed NFT",
    OwnerName: "CryptoNerd #1234",
    OwnerSorName: "CryptoNerd",
    FromBid: "1.25 ETH",
    LatestBid: "2.75 ETH",
    TotalBids: "$15,345",
    Profits: "+7.42%",
    Collection: "Space",
  },
  {
    id: 18,
    nft: space2,
    NFTalt: "Another space-themed NFT",
    OwnerName: "CryptoGeek #5678",
    OwnerSorName: "CryptoGeek",
    FromBid: "0.75 ETH",
    LatestBid: "1.50 ETH",
    TotalBids: "$8,940",
    Profits: "+12.87%",
    Collection: "Space",
  },
  {
    id: 19,
    nft: space3,
    NFTalt: "Yet another space-themed NFT",
    OwnerName: "CryptoCollector #9012",
    OwnerSorName: "CryptoCollector",
    FromBid: "3.50 ETH",
    LatestBid: "4.25 ETH",
    TotalBids: "$22,560",
    Profits: "+5.21%",
    Collection: "Space",
  },
  {
    id: 20,
    nft: space4,
    NFTalt: "A fourth space-themed NFT",
    OwnerName: "CryptoInvestor #5555",
    OwnerSorName: "CryptoInvestor",
    FromBid: "2.00 ETH",
    LatestBid: "3.50 ETH",
    TotalBids: "$19,875",
    Profits: "+8.63%",
    Collection: "Space",
  },
  {
    id: 21,
    nft: space5,
    NFTalt: "Yet another space-themed NFT",
    OwnerName: "CryptoTrader #2468",
    OwnerSorName: "CryptoTrader",
    FromBid: "1.50 ETH",
    LatestBid: "2.75 ETH",
    TotalBids: "$14,560",
    Profits: "+6.21%",
    Collection: "Space",
  },
  {
    id: 22,
    nft: space6,
    NFTalt: "A sixth space-themed NFT",
    OwnerName: "CryptoHodler #3691",
    OwnerSorName: "CryptoHodler",
    FromBid: "4.00 ETH",
    LatestBid: "5.50 ETH",
    TotalBids: "$28,120",
    Profits: "+9.87%",
    Collection: "Space",
  },
  {
    id: 23,
    nft: space7,
    NFTalt: "Another space-themed NFT",
    OwnerName: "CryptoEnthusiast #7777",
    OwnerSorName: "CryptoEnthusiast",
    FromBid: "0.50 ETH",
    LatestBid: "1.00 ETH",
    TotalBids: "$7,560",
    Profits: "+14.87%",
    Collection: "Space",
  },
  {
    id: 24,
    nft: space8,
    NFTalt: "A final space-themed NFT",
    OwnerName: "CryptoFan #8888",
    OwnerSorName: "CryptoFan",
    FromBid: "3.25 ETH",
    LatestBid: "4.50 ETH",
    TotalBids: "$24,560",
    Profits: "+11.21%",
    Collection: "Space",
  },
];
export default spaceData