import purpleHair from "../../../../assets/images/nfts/purpleHair.webp";
import Boy from "../../../../assets/images/nfts/Boy.webp";
import Cboy2Goast from "../../../../assets/images/nfts/Cboy4.webp";
import Cboy3 from "../../../../assets/images/nfts/Cboy3.webp";
import campGirl from "../../../../assets/images/nfts/campGirl.webp";
import moneyBear from "../../../../assets/images/nfts/moneyBear.webp";
import samori from "../../../../assets/images/nfts/samori.webp";
import whiteBear from "../../../../assets/images/nfts/whiteBear.webp";
const artData = [
  {
    id: 1,
    nft: purpleHair,
    NFTalt: "A purple-haired girl, NFT",
    OwnerName: "CryptoNerd #1234",
    OwnerSorName: "CryptoNerd",
    currentBid: "-1.25 ETH",
    totalBids: "15,345 ETH",
    Profits: "-7.42%",
    NEG: true,
    time: "6h 29m 13s",
  },
  {
    id: 2,
    nft: Cboy3,
    NFTalt: "A ghost boy, NFT",
    OwnerName: "PetLover #5678",
    OwnerSorName: "PetLover",
    currentBid: "0.75 ETH",
    totalBids: "6,789 ETH",
    Profits: "+3.75%",
    NEG: false,
    time: "10h 48m 42s",
  },
  {
    id: 3,
    nft: Cboy2Goast,
    NFTalt: "A boy with a hat, NFT",
    OwnerName: "FantasyFan #9999",
    OwnerSorName: "FantasyFan",
    currentBid: "10.00 ETH",
    totalBids: "150,000 ETH",
    Profits: "+20.00%",
    NEG: false,
    time: "4h 12m 28s",
  },
  {
    id: 4,
    nft: campGirl,
    NFTalt: "A girl in a tent, NFT",
    OwnerName: "ArtLover #2468",
    OwnerSorName: "ArtLover",
    currentBid: "1.50 ETH",
    totalBids: "10,000 ETH",
    Profits: "+5.00%",
    NEG: false,
    time: "2h 56m 59s",
  },
  {
    id: 5,
    nft: samori,
    NFTalt: "A samurai, NFT",
    OwnerName: "SamuraiFan #1357",
    OwnerSorName: "SamuraiFan",
    currentBid: "5.00 ETH",
    totalBids: "50,000 ETH",
    Profits: "+15.00%",
    NEG: false,
    time: "9h 19m 04s",
  },
  {
    id: 6,
    nft: whiteBear,
    NFTalt: "A white bear, NFT",
    OwnerName: "AnimalLover #8642",
    OwnerSorName: "AnimalLover",
    currentBid: "2.00 ETH",
    totalBids: "20,000 ETH",
    Profits: "+10.00%",
    NEG: false,
    time: "5h 27m 36s",
  },
  {
    id: 7,
    nft: Boy,
    NFTalt: "A boy with headphones, NFT",
    OwnerName: "MusicLover #7531",
    OwnerSorName: "MusicLover",
    currentBid: "3.00 ETH",
    totalBids: "30,000 ETH",
    Profits: "+12.50%",
    NEG: false,
    time: "1h 50m 20s",
  },
  {
    id: 8,
    nft: moneyBear,
    NFTalt: "A bear with a dollar sign, NFT",
    OwnerName: "CryptoLover #2468",
    OwnerSorName: "CryptoLover",
    currentBid: "-0.50 ETH",
    totalBids: "5,000 ETH",
    Profits: "-2.50%",
    NEG: true,
    time: "8h 33m 47s",
  },
];
export default artData;
