import more1 from "../../../../assets/images/nfts/goast1.webp";
import more2 from "../../../../assets/images/nfts/goast3.webp";
import more3 from "../../../../assets/images/nfts/goast4.webp";
import more4 from "../../../../assets/images/nfts/dogy.webp";
import more5 from "../../../../assets/images/nfts/cowboyF.webp";
import more6 from "../../../../assets/images/nfts/cowboy.webp";
import more7 from "../../../../assets/images/nfts/cowboy5.webp";
import more8 from "../../../../assets/images/nfts/cowboy4.webp";
const moreData = [
  {
    id: 41,
    nft: more1,
    NFTalt: "A goast NFT",
    OwnerName: "GoastOwner #1234",
    OwnerSorName: "GoastOwner",
    FromBid: "0.5 ETH",
    currentBid: "1.25 ETH",
    totalBids: "10,000 ETH",
    Profits: "+10.00%",
    Collection: "Goast Collection",
    time: "11h 15m 10s",
  },
  {
    id: 42,
    nft: more2,
    NFTalt: "A goast NFT",
    OwnerName: "GoastOwner #5678",
    OwnerSorName: "GoastOwner",
    FromBid: "0.75 ETH",
    currentBid: "2.00 ETH",
    totalBids: "20,000 ETH",
    Profits: "+15.00%",
    Collection: "Goast Collection",
    time: "7h 01m 55s",
  },
  {
    id: 43,
    nft: more3,
    NFTalt: "A goast NFT",
    OwnerName: "GoastOwner #9012",
    OwnerSorName: "GoastOwner",
    FromBid: "1.00 ETH",
    currentBid: "2.50 ETH",
    totalBids: "30,000 ETH",
    Profits: "+20.00%",
    Collection: "Goast Collection",
    time: "12h 04m 26s",
  },
  {
    id: 44,
    nft: more4,
    NFTalt: "A dog NFT",
    OwnerName: "DogOwner #3456",
    OwnerSorName: "DogOwner",
    FromBid: "0.25 ETH",
    currentBid: "1.00 ETH",
    totalBids: "5,000 ETH",
    Profits: "+5.00%",
    Collection: "Dog Collection",
    time: "3h 42m 31s",
  },
  {
    id: 45,
    nft: more5,
    NFTalt: "A dog NFT",
    OwnerName: "DogOwner #7890",
    OwnerSorName: "DogOwner",
    FromBid: "0.50 ETH",
    currentBid: "1.50 ETH",
    totalBids: "15,000 ETH",
    Profits: "+12.50%",
    Collection: "Dog Collection",
    time: "6h 07m 07s",
  },
  {
    id: 46,
    nft: more6,
    NFTalt: "A cowboy NFT",
    OwnerName: "CowboyOwner #2345",
    OwnerSorName: "CowboyOwner",
    FromBid: "0.75 ETH",
    currentBid: "2.25 ETH",
    totalBids: "25,000 ETH",
    Profits: "+17.50%",
    Collection: "Cowboy Collection",
    time: "10h 59m 53s",
  },
  {
    id: 47,
    nft: more7,
    NFTalt: "A cowboy NFT",
    OwnerName: "CowboyOwner #6789",
    OwnerSorName: "CowboyOwner",
    FromBid: "1.00 ETH",
    currentBid: "3.00 ETH",
    totalBids: "35,000 ETH",
    Profits: "+25.00%",
    Collection: "Cowboy Collection",
    time: "4h 34m 16s",
  },
  {
    id: 48,
    nft: more8,
    NFTalt: "A cowboy NFT",
    OwnerName: "CowboyOwner #1234",
    OwnerSorName: "CowboyOwner",
    FromBid: "0.25 ETH",
    currentBid: "0.75 ETH",
    totalBids: "2,500 ETH",
    Profits: "+2.50%",
    Collection: "Cowboy Collection",
    time: "2h 21m 39s",
  },
];
export default moreData;
