import sport1 from "../../../../assets/images/nfts/player.webp";
import sport2 from "../../../../assets/images/nfts/player2.webp";
import sport3 from "../../../../assets/images/nfts/player3.webp";
import sport4 from "../../../../assets/images/nfts/player4.webp";
import sport5 from "../../../../assets/images/nfts/player5.webp";
import sport6 from "../../../../assets/images/nfts/player6.webp";
import sport7 from "../../../../assets/images/nfts/player7.webp";
import sport8 from "../../../../assets/images/nfts/player8.webp";
const sportData = [
  {
    id: 33,
    nft: sport1,
    NFTalt: "A sport NFT",
    OwnerName: "SportOwner #1234",
    OwnerSorName: "SportOwner",
    FromBid: "0.5 ETH",
    currentBid: "1.25 ETH",
    totalBids: "$10,000",
    Profits: "+10.00%",
    Collection: "Sports Collection",
    time: "6h 29m 68s",
  },
  {
    id: 34,
    nft: sport2,
    NFTalt: "A sport NFT",
    OwnerName: "SportOwner #5678",
    OwnerSorName: "SportOwner",
    FromBid: "0.75 ETH",
    currentBid: "2.00 ETH",
    totalBids: "$20,000",
    Profits: "+15.00%",
    Collection: "Sports Collection",
    time: "2h 45m 71s",
    
  },
  {
    id: 35,
    nft: sport3,
    NFTalt: "A sport NFT",
    OwnerName: "SportOwner #9012",
    OwnerSorName: "SportOwner",
    FromBid: "1.00 ETH",
    currentBid: "2.50 ETH",
    totalBids: "$30,000",
    Profits: "+20.00%",
    Collection: "Sports Collection",
    time: "9h 12m 42s",
  },
  {
    id: 36,
    nft: sport4,
    NFTalt: "A sport NFT",
    OwnerName: "SportOwner #3456",
    OwnerSorName: "SportOwner",
    FromBid: "0.25 ETH",
    currentBid: "1.00 ETH",
    totalBids: "$5,000",
    Profits: "+5.00%",
    Collection: "Sports Collection",
    time: "5h 18m 93s",
  },
  {
    id: 37,
    nft: sport5,
    NFTalt: "A sport NFT",
    OwnerName: "SportOwner #7890",
    OwnerSorName: "SportOwner",
    FromBid: "0.50 ETH",
    currentBid: "1.50 ETH",
    totalBids: "$15,000",
    Profits: "+12.50%",
    Collection: "Sports Collection",
    time: "10h 28m 64s",
  },
  {
    id: 38,
    nft: sport6,
    NFTalt: "A sport NFT",
    OwnerName: "SportOwner #2345",
    OwnerSorName: "SportOwner",
    FromBid: "0.75 ETH",
    currentBid: "2.25 ETH",
    totalBids: "$25,000",
    Profits: "+17.50%",
    Collection: "Sports Collection",
    time: "3h 59m 77s",
  },
  {
    id: 39,
    nft: sport7,
    NFTalt: "A sport NFT",
    OwnerName: "SportOwner #6789",
    OwnerSorName: "SportOwner",
    FromBid: "1.00 ETH",
    currentBid: "3.00 ETH",
    totalBids: "$35,000",
    Profits: "+25.00%",
    Collection: "Sports Collection",
    time: "7h 15m 68s",
  },
  {
    id: 40,
    nft: sport8,
    NFTalt: "A sport NFT",
    OwnerName: "SportOwner #1234",
    OwnerSorName: "SportOwner",
    FromBid: "0.25 ETH",
    currentBid: "0.75 ETH",
    totalBids: "$2,500",
    Profits: "+2.50%",
    Collection: "Sports Collection",
    time: "4h 50m 77s",
  },
];
export default sportData;
