const data = [
  {
    nft: require("./../assets/images/nfts/MonBan.png"),
    imgOwner: require("./../assets/images/Users/Verifi.png"),
    imgName: "HAPE #6959",
    imgSmName: "HAPES PRIME",
    CurrentPrince: "5.758 ETH",
    TotalPrince: "$5758.31",
    Profits: "+12.45%",
  },
  {
    nft: require("./../assets/images/nfts/owl.webp"),
    imgOwner: require("./../assets/images/Users/Verifi.png"),
    imgName: "HAPE #6959",
    imgSmName: "HAPES PRIME",
    CurrentPrice: "3.142 ETH",
    TotalPrice: "$5234.51",
    Profits: "+48.55%",
  },
  {
    nft: require("./../assets/images/nfts/cheap.webp"),
    imgOwner: require("./../assets/images/Users/ahbal.png"),
    imgName: "alokir #3154",
    imgSmName: "alokir shaow",
    CurrentPrice: "6.142 ETH",
    TotalPrice: "$99,524.92",
    Profits: "+11.12%",
  },
  {
    nft: require("./../assets/images/nfts/Cool.png"),
    imgOwner: require("./../assets/images/Users/chanda.png"),
    imgName: "Chanda #2412",
    imgSmName: "Chanda chanda",
    CurrentPrice: "2.1245 ETH",
    TotalPrice: "$19,534.33",
    Profits: "+2.99%",
  },
  {
    nft: require("./../assets/images/nfts/crocPi.webp"),
    imgOwner: require("./../assets/images/Users/MSRT.png"),
    imgName: "msrt #8831",
    imgSmName: "msrt mosrt",
    CurrentPrice: "8.231 ETH",
    TotalPrice: "$21,421.48",
    Profits: "+78.24%",
  },
];
